import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "bn" | "en" | "ctg" | "noakhali";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  bn: {
    // Common
    home: "হোম",
    settings: "সেটিংস",
    back: "ফিরে যান",
    save: "সংরক্ষণ করুন",
    cancel: "বাতিল",
    loading: "লোড হচ্ছে...",
    error: "ত্রুটি হয়েছে",
    success: "সফল হয়েছে",
    wait: "অপেক্ষা করুন...",
    refresh: "রিফ্রেশ",
    search: "খুঁজুন",
    all: "সব",
    
    // App
    appName: "agriশক্তি",
    tagline: "মাটি, মানুষ, প্রযুক্তি – কৃষির নতুন শক্তি",
    taglineShort: "কৃষির নতুন শক্তি",
    beta: "বেটা",
    
    // Services
    diseaseDetection: "রোগ শনাক্তকরণ",
    diseaseDesc: "ফসলের রোগ চিনুন",
    fertilizerScan: "সার স্ক্যান",
    fertilizerDesc: "সার যাচাই করুন",
    pestMap: "পোকার ম্যাপ",
    pestDesc: "এলাকার পোকা দেখুন",
    aiAssistant: "AI সহায়ক",
    aiDesc: "কৃষি পরামর্শ নিন",
    marketPrice: "বাজার দর",
    marketDesc: "বাজার মূল্য দেখুন",
    weather: "আবহাওয়া",
    weatherDesc: "আবহাওয়া পূর্বাভাস",
    satellite: "স্যাটেলাইট ভিশন",
    satelliteDesc: "NDVI ম্যাপ দেখুন",
    calendar: "ফার্মিং ক্যালেন্ডার",
    calendarDesc: "কাজের সময়সূচী",
    calendarBanglaEng: "বাংলা/ইংরেজি ক্যালেন্ডার",
    compass: "কম্পাস",
    compassDesc: "দিক নির্ণয়",
    landMap: "জমির ম্যাপ",
    landMapDesc: "স্যাটেলাইট ম্যাপ",
    cropSchedule: "ফসলের সময়সূচী",
    machine: "যন্ত্র অপ্টিমাইজার",
    machineDesc: "ট্রাক্টর/টিলার গাইড",
    npkCalculator: "সার ক্যালকুলেটর",
    npkDesc: "NPK ডোজ হিসাব",
    climateAlert: "জলবায়ু সতর্কতা",
    climateDesc: "দুর্যোগ সতর্কতা",
    govServices: "সরকারি সেবা",
    govDesc: "ভর্তুকি ও ঋণ",
    storage: "গুদাম ব্যবস্থাপনা",
    storageDesc: "ফসল সংরক্ষণ",
    history: "ফসল ইতিহাস",
    historyDesc: "আগের স্ক্যান দেখুন",
    rewards: "পুরস্কার",
    rewardsDesc: "ব্যাজ ও পয়েন্ট",
    fertilizerAdvice: "সার পরামর্শ",
    fertAdviceDesc: "সার সুপারিশ",
    knowledge: "কৃষি জ্ঞান",
    knowledgeDesc: "শিখুন ও জানুন",
    community: "কমিউনিটি",
    communityDesc: "কৃষক সংঘ",
    appGuide: "অ্যাপ গাইড",
    guideDesc: "টিউটোরিয়াল দেখুন",
    landCalculator: "জমি হিসাব",
    landDesc: "জমির মাপ ও দাম",
    impactAnalytics: "প্রভাব বিশ্লেষণ",
    impactDesc: "সমস্যা সমাধান চার্ট",
    
    // Bottom Nav
    scanner: "স্ক্যানার",
    aiChat: "AI চ্যাট",
    support: "সাপোর্ট",
    
    // Header
    loggedIn: "লগইন করা আছে",
    welcome: "স্বাগতম!",
    welcomeBack: "স্বাগতম!",
    getStarted: "শুরু করুন",
    createAccount: "অ্যাকাউন্ট তৈরি করুন",
    account: "অ্যাকাউন্ট",
    profile: "প্রোফাইল",
    logout: "লগআউট",
    login: "লগইন / রেজিস্টার",
    loginTitle: "লগইন করুন",
    registerTitle: "রেজিস্টার করুন",
    findingLocation: "লোকেশন খুঁজছি...",
    adminDashboard: "অ্যাডমিন ড্যাশবোর্ড",
    
    // Stats
    scans: "স্ক্যান",
    level: "লেভেল",
    rank: "র‍্যাংক",
    
    // Tips
    todayTip: "আজকের টিপস",
    
    // Market
    rice: "ধান",
    potato: "আলু",
    onion: "পেঁয়াজ",
    weeklyAvg: "সাপ্তাহিক গড়",
    perKg: "টাকা/কেজি",
    
    // Weather
    humidity: "আর্দ্রতা",
    wind: "বাতাস",
    feelsLike: "অনুভূত",
    
    // Settings
    customizeApp: "অ্যাপ কাস্টমাইজ করুন",
    language: "ভাষা",
    bangla: "বাংলা",
    english: "English",
    chittagongian: "চট্টগ্রামী",
    noakhalian: "নোয়াখালী",
    notifications: "নোটিফিকেশন",
    pushNotifications: "পুশ নোটিফিকেশন",
    weatherMarketUpdate: "আবহাওয়া ও বাজার আপডেট",
    smsNotifications: "SMS নোটিফিকেশন",
    importantAlerts: "গুরুত্বপূর্ণ সতর্কতা",
    namePhone: "নাম ও ফোন নম্বর",
    privacy: "গোপনীয়তা",
    dataProtection: "ডাটা সুরক্ষা সেটিংস",
    help: "সাহায্য",
    faq: "প্রশ্ন ও উত্তর",
    aboutApp: "অ্যাপ সম্পর্কে",
    version: "সংস্করণ ১.০.০",
    aiAssistantFull: "বাংলার কৃষকের AI সহকারী",
    createdBy: "Created by TEAM_NEWBIES",
    selectLanguage: "ভাষা নির্বাচন করুন",
    chooseLanguage: "আপনার পছন্দের ভাষা বেছে নিন",
    enterPhone: "ফোন নম্বর দিন",
    phoneNumber: "ফোন নম্বর",
    smsSaved: "SMS নোটিফিকেশন সক্রিয় হয়েছে",
    smsDisabled: "SMS নোটিফিকেশন বন্ধ হয়েছে",
    languageChanged: "ভাষা পরিবর্তন হয়েছে",
    validPhone: "সঠিক ফোন নম্বর দিন",
    smsDescription: "SMS নোটিফিকেশন পেতে আপনার মোবাইল নম্বর দিন",
    theme: "থিম",
    darkLightMode: "ডার্ক/লাইট মোড",
    darkModeOn: "ডার্ক মোড চালু আছে",
    lightModeOn: "লাইট মোড চালু আছে",
    themeChanged: "থিম পরিবর্তন হয়েছে",
    
    // Land Calculator
    landCalculatorTitle: "জমি হিসাব ক্যালকুলেটর",
    landCalculatorDesc: "জমির মাপ ও মূল্য হিসাব করুন",
    enterLandSize: "জমির পরিমাণ দিন",
    selectUnit: "একক নির্বাচন করুন",
    bigha: "বিঘা",
    katha: "কাঠা",
    decimal: "শতক",
    acre: "একর",
    sqFeet: "বর্গফুট",
    sqMeter: "বর্গমিটার",
    calculate: "হিসাব করুন",
    result: "ফলাফল",
    pricePerUnit: "প্রতি একক মূল্য (টাকা)",
    totalPrice: "মোট মূল্য",
    conversion: "রূপান্তর",
    reset: "রিসেট",
    
    // Offline
    offlineMode: "অফলাইন মোড",
    offlineMessage: "ইন্টারনেট নেই। সীমিত সুবিধা পাবেন।",
    
    // Chat
    askQuestion: "প্রশ্ন করুন...",
    voiceInput: "ভয়েস ইনপুট",
    send: "পাঠান",
    chatGreeting: "আসসালামু আলাইকুম! আমি agriশক্তি AI। আপনার কৃষি সমস্যায় সাহায্য করতে প্রস্তুত। কী জানতে চান? 🌾",
    agriExpert: "কৃষি বিশেষজ্ঞ সহকারী",
    suggestedQuestions: "প্রস্তাবিত প্রশ্ন",
    justNow: "এইমাত্র",
    listening: "শুনছি...",
    speakBengali: "বাংলায় কথা বলুন",
    typeOrSpeak: "বাংলায় লিখুন বা বলুন...",
    voiceHeard: "কথা শোনা হয়েছে",
    voiceError: "ভয়েস ত্রুটি",
    chatHistoryCleared: "চ্যাট ইতিহাস মুছে ফেলা হয়েছে",
    clearChatHistory: "চ্যাট ইতিহাস মুছুন",
    clickMicToSpeak: "মাইক বাটনে ক্লিক করে বাংলায় কথা বলুন",
    sorryTempProblem: "দুঃখিত, সাময়িক সমস্যা হয়েছে। আবার চেষ্টা করুন।",
    errorGettingAnswer: "উত্তর পেতে সমস্যা হয়েছে। আবার চেষ্টা করুন।",
    sorryCantAnswer: "দুঃখিত, উত্তর দিতে পারছি না।",
    listen: "শুনুন",
    chatQuestion1: "ধানের পাতা হলুদ হয়ে যাচ্ছে কেন?",
    chatQuestion2: "কখন সার দেওয়া উচিত?",
    chatQuestion3: "বৃষ্টিতে ফসল রক্ষা করব কীভাবে?",
    chatQuestion4: "পোকামাকড় দমন করব কীভাবে?",
    
    // Auth
    email: "ইমেইল",
    password: "পাসওয়ার্ড",
    fullName: "পুরো নাম",
    yourEmail: "আপনার ইমেইল",
    yourPassword: "আপনার পাসওয়ার্ড",
    yourFullName: "আপনার পূর্ণ নাম",
    minPassword: "কমপক্ষে ৬ অক্ষর",
    bloodGroup: "রক্তের গ্রুপ",
    nationality: "জাতীয়তা",
    bangladeshi: "বাংলাদেশী",
    indian: "ভারতীয়",
    other: "অন্যান্য",
    select: "নির্বাচন",
    uploadPhoto: "ছবি আপলোড",
    loginToAccount: "আপনার অ্যাকাউন্টে লগইন করুন",
    createNewAccount: "নতুন অ্যাকাউন্ট তৈরি করুন",
    openAccount: "অ্যাকাউন্ট খুলুন",
    loginBtn: "লগইন করুন",
    signupBtn: "সাইনআপ করুন",
    loginSuccess: "সফলভাবে লগইন হয়েছে",
    logoutSuccess: "সফলভাবে লগআউট হয়েছে",
    logoutError: "লগআউট করতে সমস্যা হয়েছে",
    accountCreated: "সফলভাবে অ্যাকাউন্ট তৈরি হয়েছে!",
    fillAllFields: "সব তথ্য পূরণ করুন",
    fillNameEmailPass: "নাম, ইমেইল এবং পাসওয়ার্ড পূরণ করুন",
    wrongEmailPass: "ইমেইল বা পাসওয়ার্ড ভুল হয়েছে",
    emailAlreadyUsed: "এই ইমেইল দিয়ে আগে অ্যাকাউন্ট খোলা হয়েছে",
    somethingWrong: "কিছু সমস্যা হয়েছে, আবার চেষ্টা করুন",
    
    // Profile
    xpPoints: "XP পয়েন্ট",
    totalScans: "মোট স্ক্যান",
    daysActive: "সক্রিয় দিন",
    diseasesDetected: "রোগ শনাক্ত",
    editProfile: "প্রোফাইল সম্পাদনা",
    
    // Common Actions
    view: "দেখুন",
    viewAll: "সব দেখুন",
    more: "আরো",
    less: "কম",
    tryAgain: "আবার চেষ্টা করুন",
    close: "বন্ধ করুন",
    confirm: "নিশ্চিত করুন",
    delete: "মুছুন",
    edit: "সম্পাদনা",
    add: "যোগ করুন",
  },
  en: {
    // Common
    home: "Home",
    settings: "Settings",
    back: "Go Back",
    save: "Save",
    cancel: "Cancel",
    loading: "Loading...",
    error: "Error occurred",
    success: "Success",
    wait: "Please wait...",
    refresh: "Refresh",
    search: "Search",
    all: "All",
    
    // App
    appName: "agriShokti",
    tagline: "Soil, People, Technology – New Power of Agriculture",
    taglineShort: "New Power of Agriculture",
    beta: "Beta",
    
    // Services
    diseaseDetection: "Disease Detection",
    diseaseDesc: "Identify crop diseases",
    fertilizerScan: "Fertilizer Scan",
    fertilizerDesc: "Verify fertilizers",
    pestMap: "Pest Map",
    pestDesc: "View area pests",
    aiAssistant: "AI Assistant",
    aiDesc: "Get farming advice",
    marketPrice: "Market Price",
    marketDesc: "View market prices",
    weather: "Weather",
    weatherDesc: "Weather forecast",
    satellite: "Satellite Vision",
    satelliteDesc: "View NDVI maps",
    calendar: "Farming Calendar",
    calendarDesc: "Work schedule",
    calendarBanglaEng: "Bangla/English Calendar",
    compass: "Compass",
    compassDesc: "Direction finder",
    landMap: "Land Map",
    landMapDesc: "Satellite Map",
    cropSchedule: "Crop Schedule",
    machine: "Machine Optimizer",
    machineDesc: "Tractor/Tiller guide",
    npkCalculator: "Fertilizer Calculator",
    npkDesc: "NPK dose calculation",
    climateAlert: "Climate Alert",
    climateDesc: "Disaster warnings",
    govServices: "Gov Services",
    govDesc: "Subsidies & loans",
    storage: "Storage Management",
    storageDesc: "Crop storage",
    history: "Crop History",
    historyDesc: "View past scans",
    rewards: "Rewards",
    rewardsDesc: "Badges & points",
    fertilizerAdvice: "Fertilizer Advice",
    fertAdviceDesc: "Fertilizer recommendations",
    knowledge: "Agricultural Knowledge",
    knowledgeDesc: "Learn & know",
    community: "Community",
    communityDesc: "Farmer community",
    appGuide: "App Guide",
    guideDesc: "View tutorials",
    landCalculator: "Land Calculator",
    landDesc: "Land measurement & price",
    impactAnalytics: "Impact Analytics",
    impactDesc: "Problem solving charts",
    
    // Bottom Nav
    scanner: "Scanner",
    aiChat: "AI Chat",
    support: "Support",
    
    // Header
    loggedIn: "Logged in as",
    welcome: "Welcome!",
    welcomeBack: "Welcome back!",
    getStarted: "Get Started",
    createAccount: "Create an account",
    account: "Account",
    profile: "Profile",
    logout: "Logout",
    login: "Login / Register",
    loginTitle: "Login",
    registerTitle: "Register",
    findingLocation: "Finding location...",
    adminDashboard: "Admin Dashboard",
    
    // Stats
    scans: "Scans",
    level: "Level",
    rank: "Rank",
    
    // Tips
    todayTip: "Today's Tips",
    
    // Market
    rice: "Rice",
    potato: "Potato",
    onion: "Onion",
    weeklyAvg: "Weekly Avg",
    perKg: "Taka/kg",
    
    // Weather
    humidity: "Humidity",
    wind: "Wind",
    feelsLike: "Feels like",
    
    // Settings
    customizeApp: "Customize your app",
    language: "Language",
    bangla: "বাংলা",
    english: "English",
    chittagongian: "Chittagongian",
    noakhalian: "Noakhalian",
    notifications: "Notifications",
    pushNotifications: "Push Notifications",
    weatherMarketUpdate: "Weather & Market Updates",
    smsNotifications: "SMS Notifications",
    importantAlerts: "Important Alerts",
    namePhone: "Name & Phone Number",
    privacy: "Privacy",
    dataProtection: "Data Protection Settings",
    help: "Help",
    faq: "FAQ",
    aboutApp: "About App",
    version: "Version 1.0.0",
    aiAssistantFull: "AI Assistant for Bangladesh Farmers",
    createdBy: "Created by TEAM_NEWBIES",
    selectLanguage: "Select Language",
    chooseLanguage: "Choose your preferred language",
    enterPhone: "Enter Phone Number",
    phoneNumber: "Phone Number",
    smsSaved: "SMS notifications enabled",
    smsDisabled: "SMS notifications disabled",
    languageChanged: "Language changed",
    validPhone: "Enter a valid phone number",
    smsDescription: "Enter your mobile number to receive SMS notifications",
    theme: "Theme",
    darkLightMode: "Dark/Light Mode",
    darkModeOn: "Dark mode is on",
    lightModeOn: "Light mode is on",
    themeChanged: "Theme changed",
    
    // Land Calculator
    landCalculatorTitle: "Land Calculator",
    landCalculatorDesc: "Calculate land measurement & price",
    enterLandSize: "Enter land size",
    selectUnit: "Select unit",
    bigha: "Bigha",
    katha: "Katha",
    decimal: "Decimal",
    acre: "Acre",
    sqFeet: "Sq Feet",
    sqMeter: "Sq Meter",
    calculate: "Calculate",
    result: "Result",
    pricePerUnit: "Price per unit (Taka)",
    totalPrice: "Total Price",
    conversion: "Conversion",
    reset: "Reset",
    
    // Offline
    offlineMode: "Offline Mode",
    offlineMessage: "No internet. Limited features available.",
    
    // Chat
    askQuestion: "Ask a question...",
    voiceInput: "Voice Input",
    send: "Send",
    chatGreeting: "Assalamualaikum! I'm agriShokti AI. Ready to help with your farming problems. What would you like to know? 🌾",
    agriExpert: "Agriculture Expert Assistant",
    suggestedQuestions: "Suggested Questions",
    justNow: "Just now",
    listening: "Listening...",
    speakBengali: "Speak in Bengali",
    typeOrSpeak: "Type or speak in Bengali...",
    voiceHeard: "Voice recorded",
    voiceError: "Voice error",
    chatHistoryCleared: "Chat history cleared",
    clearChatHistory: "Clear chat history",
    clickMicToSpeak: "Click mic button to speak in Bengali",
    sorryTempProblem: "Sorry, temporary problem. Please try again.",
    errorGettingAnswer: "Error getting answer. Please try again.",
    sorryCantAnswer: "Sorry, unable to answer.",
    listen: "Listen",
    chatQuestion1: "Why are rice leaves turning yellow?",
    chatQuestion2: "When should I apply fertilizer?",
    chatQuestion3: "How to protect crops from rain?",
    chatQuestion4: "How to control pests?",
    
    // Auth
    email: "Email",
    password: "Password",
    fullName: "Full Name",
    yourEmail: "Your email",
    yourPassword: "Your password",
    yourFullName: "Your full name",
    minPassword: "At least 6 characters",
    bloodGroup: "Blood Group",
    nationality: "Nationality",
    bangladeshi: "Bangladeshi",
    indian: "Indian",
    other: "Other",
    select: "Select",
    uploadPhoto: "Upload Photo",
    loginToAccount: "Login to your account",
    createNewAccount: "Create a new account",
    openAccount: "Open Account",
    loginBtn: "Login",
    signupBtn: "Sign Up",
    loginSuccess: "Logged in successfully",
    logoutSuccess: "Logged out successfully",
    logoutError: "Error logging out",
    accountCreated: "Account created successfully!",
    fillAllFields: "Please fill all fields",
    fillNameEmailPass: "Please fill name, email and password",
    wrongEmailPass: "Wrong email or password",
    emailAlreadyUsed: "This email is already registered",
    somethingWrong: "Something went wrong, please try again",
    
    // Profile
    xpPoints: "XP Points",
    totalScans: "Total Scans",
    daysActive: "Days Active",
    diseasesDetected: "Diseases Detected",
    editProfile: "Edit Profile",
    
    // Common Actions
    view: "View",
    viewAll: "View All",
    more: "More",
    less: "Less",
    tryAgain: "Try Again",
    close: "Close",
    confirm: "Confirm",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
  },
  ctg: {
    // Chittagongian dialect
    // Common
    home: "ঘর",
    settings: "সেটিংস",
    back: "ফিরা যাও",
    save: "রাখো",
    cancel: "বাদ দে",
    loading: "লোড অইতাছে...",
    error: "সমস্যা অইছে",
    success: "অইয়া গেছে",
    wait: "ধৈর্য ধর...",
    refresh: "রিফ্রেশ",
    search: "খোঁজ",
    all: "সগ্গোলা",
    
    // App
    appName: "agriশক্তি",
    tagline: "মাডি, মানুষ, প্রযুক্তি – খেতির নুয়া শক্তি",
    taglineShort: "খেতির নুয়া শক্তি",
    beta: "বেটা",
    
    // Services
    diseaseDetection: "রোগ চিনা",
    diseaseDesc: "ফসলর রোগ চিন",
    fertilizerScan: "সার স্ক্যান",
    fertilizerDesc: "সার যাচাই গর",
    pestMap: "পোকার ম্যাপ",
    pestDesc: "এলাকার পোকা দেখ",
    aiAssistant: "AI সাহায্যকারী",
    aiDesc: "খেতির পরামর্শ নে",
    marketPrice: "বাজার দাম",
    marketDesc: "বাজার দাম দেখ",
    weather: "আবহাওয়া",
    weatherDesc: "আবহাওয়া খবর",
    satellite: "স্যাটেলাইট ভিশন",
    satelliteDesc: "NDVI ম্যাপ দেখ",
    calendar: "খেতির ক্যালেন্ডার",
    calendarDesc: "কাজর সময়",
    calendarBanglaEng: "বাংলা/ইংরাজী ক্যালেন্ডার",
    compass: "কম্পাস",
    compassDesc: "দিক খোঁজ",
    landMap: "জমির ম্যাপ",
    landMapDesc: "স্যাটেলাইট ম্যাপ",
    cropSchedule: "ফসলর সময়",
    machine: "যন্ত্র অপ্টিমাইজার",
    machineDesc: "ট্রাক্টর গাইড",
    npkCalculator: "সার ক্যালকুলেটর",
    npkDesc: "NPK ডোজ হিসাব",
    climateAlert: "জলবায়ু সতর্কতা",
    climateDesc: "দুর্যোগ সতর্কতা",
    govServices: "সরকারি সেবা",
    govDesc: "ভর্তুকি ও ঋণ",
    storage: "গুদাম ব্যবস্থাপনা",
    storageDesc: "ফসল রাখা",
    history: "ফসল ইতিহাস",
    historyDesc: "আগের স্ক্যান দেখ",
    rewards: "পুরস্কার",
    rewardsDesc: "ব্যাজ ও পয়েন্ট",
    fertilizerAdvice: "সার পরামর্শ",
    fertAdviceDesc: "সার সুপারিশ",
    knowledge: "খেতির জ্ঞান",
    knowledgeDesc: "শিখ ও জান",
    community: "কমিউনিটি",
    communityDesc: "কৃষক সংঘ",
    appGuide: "অ্যাপ গাইড",
    guideDesc: "টিউটোরিয়াল দেখ",
    landCalculator: "জমি হিসাব",
    landDesc: "জমির মাপ ও দাম",
    impactAnalytics: "প্রভাব বিশ্লেষণ",
    impactDesc: "সমস্যা সমাধান চার্ট",
    
    // Bottom Nav
    scanner: "স্ক্যানার",
    aiChat: "AI চ্যাট",
    support: "সাপোর্ট",
    
    // Header
    loggedIn: "লগইন অইছো",
    welcome: "স্বাগতম!",
    welcomeBack: "স্বাগতম!",
    getStarted: "শুরু গর",
    createAccount: "একাউন্ট খোল",
    account: "একাউন্ট",
    profile: "প্রোফাইল",
    logout: "লগআউট",
    login: "লগইন / রেজিস্টার",
    loginTitle: "লগইন গর",
    registerTitle: "রেজিস্টার গর",
    findingLocation: "লোকেশন খুঁজতাছি...",
    adminDashboard: "অ্যাডমিন ড্যাশবোর্ড",
    
    // Stats
    scans: "স্ক্যান",
    level: "লেভেল",
    rank: "র‍্যাংক",
    
    // Tips
    todayTip: "আইজকার টিপস",
    
    // Market
    rice: "ধান",
    potato: "আলু",
    onion: "পিঁয়াজ",
    weeklyAvg: "সাপ্তাহিক গড়",
    perKg: "টেহা/কেজি",
    
    // Weather
    humidity: "আর্দ্রতা",
    wind: "বাতাস",
    feelsLike: "অনুভব",
    
    // Settings
    customizeApp: "অ্যাপ কাস্টমাইজ গর",
    language: "ভাষা",
    bangla: "বাংলা",
    english: "English",
    chittagongian: "চাঁটগাঁইয়া",
    noakhalian: "নোয়াখাইল্যা",
    notifications: "নোটিফিকেশন",
    pushNotifications: "পুশ নোটিফিকেশন",
    weatherMarketUpdate: "আবহাওয়া ও বাজার আপডেট",
    smsNotifications: "SMS নোটিফিকেশন",
    importantAlerts: "গুরুত্বপূর্ণ সতর্কতা",
    namePhone: "নাম ও ফোন নম্বর",
    privacy: "গোপনীয়তা",
    dataProtection: "ডাটা সুরক্ষা সেটিংস",
    help: "সাহায্য",
    faq: "প্রশ্ন ও উত্তর",
    aboutApp: "অ্যাপ সম্পর্কে",
    version: "সংস্করণ ১.০.০",
    aiAssistantFull: "বাংলার কৃষকর AI সহকারী",
    createdBy: "Created by TEAM_NEWBIES",
    selectLanguage: "ভাষা বাছাই গর",
    chooseLanguage: "তোর পছন্দর ভাষা বাছাই গর",
    enterPhone: "ফোন নম্বর দে",
    phoneNumber: "ফোন নম্বর",
    smsSaved: "SMS নোটিফিকেশন চালু অইছে",
    smsDisabled: "SMS নোটিফিকেশন বন্ধ অইছে",
    languageChanged: "ভাষা বদলাইছে",
    validPhone: "ঠিক ফোন নম্বর দে",
    smsDescription: "SMS পাইতে মোবাইল নম্বর দে",
    theme: "থিম",
    darkLightMode: "ডার্ক/লাইট মোড",
    darkModeOn: "ডার্ক মোড চালু",
    lightModeOn: "লাইট মোড চালু",
    themeChanged: "থিম বদলাইছে",
    
    // Land Calculator
    landCalculatorTitle: "জমি হিসাব ক্যালকুলেটর",
    landCalculatorDesc: "জমির মাপ ও দাম হিসাব গর",
    enterLandSize: "জমির পরিমাণ দে",
    selectUnit: "একক বাছাই গর",
    bigha: "বিঘা",
    katha: "কাঠা",
    decimal: "শতক",
    acre: "একর",
    sqFeet: "বর্গফুট",
    sqMeter: "বর্গমিটার",
    calculate: "হিসাব গর",
    result: "ফলাফল",
    pricePerUnit: "প্রতি একক দাম (টেহা)",
    totalPrice: "মোট দাম",
    conversion: "রূপান্তর",
    reset: "রিসেট",
    
    // Offline
    offlineMode: "অফলাইন মোড",
    offlineMessage: "নেট নাই। সীমিত সুবিধা পাইবা।",
    
    // Chat
    askQuestion: "জিগাও...",
    voiceInput: "ভয়েস ইনপুট",
    send: "পাঠাও",
    chatGreeting: "আসসালামু আলাইকুম! আঁই agriশক্তি AI। তোর খেতির সমস্যায় সাহায্য করতে রেডি। কি জানতে চাও? 🌾",
    agriExpert: "খেতির বিশেষজ্ঞ সহকারী",
    suggestedQuestions: "প্রস্তাবিত প্রশ্ন",
    justNow: "এহনই",
    listening: "শুনতাছি...",
    speakBengali: "বাংলায় কথা কও",
    typeOrSpeak: "বাংলায় লেখ বা কও...",
    voiceHeard: "কথা শোনা অইছে",
    voiceError: "ভয়েস সমস্যা",
    chatHistoryCleared: "চ্যাট ইতিহাস মুছা গেছে",
    clearChatHistory: "চ্যাট ইতিহাস মুছ",
    clickMicToSpeak: "মাইক বাটনে ক্লিক গইরা বাংলায় কথা কও",
    sorryTempProblem: "মাফ গর, সাময়িক সমস্যা। আবার চেষ্টা গর।",
    errorGettingAnswer: "উত্তর পাইতে সমস্যা। আবার চেষ্টা গর।",
    sorryCantAnswer: "মাফ গর, উত্তর দিতে পারতাছি না।",
    listen: "শোন",
    chatQuestion1: "ধানের পাতা হলুদ অইতাছে ক্যান?",
    chatQuestion2: "কহন সার দেওন ঠিক?",
    chatQuestion3: "বৃষ্টিতে ফসল বাঁচামু ক্যামনে?",
    chatQuestion4: "পোকামাকড় মারমু ক্যামনে?",
    
    // Auth
    email: "ইমেইল",
    password: "পাসওয়ার্ড",
    fullName: "পুরা নাম",
    yourEmail: "তোর ইমেইল",
    yourPassword: "তোর পাসওয়ার্ড",
    yourFullName: "তোর পুরা নাম",
    minPassword: "কম অইলেও ৬ অক্ষর",
    bloodGroup: "রক্তের গ্রুপ",
    nationality: "জাতীয়তা",
    bangladeshi: "বাংলাদেশী",
    indian: "ভারতীয়",
    other: "অন্যান্য",
    select: "বাছাই গর",
    uploadPhoto: "ছবি দে",
    loginToAccount: "তোর একাউন্টে লগইন গর",
    createNewAccount: "নতুন একাউন্ট খোল",
    openAccount: "একাউন্ট খোল",
    loginBtn: "লগইন গর",
    signupBtn: "সাইনআপ গর",
    loginSuccess: "লগইন অইছে",
    logoutSuccess: "লগআউট অইছে",
    logoutError: "লগআউট করতে সমস্যা অইছে",
    accountCreated: "একাউন্ট খোলা অইছে!",
    fillAllFields: "সগ্গোলা তথ্য দে",
    fillNameEmailPass: "নাম, ইমেইল আর পাসওয়ার্ড দে",
    wrongEmailPass: "ইমেইল বা পাসওয়ার্ড ভুল",
    emailAlreadyUsed: "এই ইমেইল দিয়া আগেই একাউন্ট আছে",
    somethingWrong: "কিছু সমস্যা অইছে, আবার চেষ্টা গর",
    
    // Profile
    xpPoints: "XP পয়েন্ট",
    totalScans: "মোট স্ক্যান",
    daysActive: "সক্রিয় দিন",
    diseasesDetected: "রোগ শনাক্ত",
    editProfile: "প্রোফাইল সম্পাদনা",
    
    // Common Actions
    view: "দেখ",
    viewAll: "সগ্গোলা দেখ",
    more: "আরো",
    less: "কম",
    tryAgain: "আবার চেষ্টা গর",
    close: "বন্ধ গর",
    confirm: "নিশ্চিত গর",
    delete: "মুছ",
    edit: "সম্পাদনা",
    add: "যোগ গর",
  },
  noakhali: {
    // Noakhali dialect
    // Common
    home: "বাড়ি",
    settings: "সেটিংস",
    back: "ফিরাইয়া যাও",
    save: "রাখ",
    cancel: "বাদ দে",
    loading: "লোড হইতাসে...",
    error: "সমস্যা হইসে",
    success: "হইয়া গেসে",
    wait: "ধৈর্য ধর...",
    refresh: "রিফ্রেশ",
    search: "খোঁজ",
    all: "সব",
    
    // App
    appName: "agriশক্তি",
    tagline: "মাটি, মানুষ, প্রযুক্তি – কৃষির নয়া শক্তি",
    taglineShort: "কৃষির নয়া শক্তি",
    beta: "বেটা",
    
    // Services
    diseaseDetection: "রোগ শনাক্ত",
    diseaseDesc: "ফসলের রোগ চিন",
    fertilizerScan: "সার স্ক্যান",
    fertilizerDesc: "সার যাসাই কর",
    pestMap: "পোকার ম্যাপ",
    pestDesc: "এলাকার পোকা দেখ",
    aiAssistant: "AI সাহায্য",
    aiDesc: "কৃষি পরামর্শ লও",
    marketPrice: "বাজার দাম",
    marketDesc: "বাজার দাম দেখ",
    weather: "আবহাওয়া",
    weatherDesc: "আবহাওয়া খবর",
    satellite: "স্যাটেলাইট ভিশন",
    satelliteDesc: "NDVI ম্যাপ দেখ",
    calendar: "খেতি ক্যালেন্ডার",
    calendarDesc: "কাজের সময়",
    calendarBanglaEng: "বাংলা/ইংরাজী ক্যালেন্ডার",
    compass: "কম্পাস",
    compassDesc: "দিক খোঁজ",
    landMap: "জমির ম্যাপ",
    landMapDesc: "স্যাটেলাইট ম্যাপ",
    cropSchedule: "ফসলের সময়",
    machine: "যন্ত্র অপ্টিমাইজার",
    machineDesc: "ট্রাক্টর গাইড",
    npkCalculator: "সার ক্যালকুলেটর",
    npkDesc: "NPK ডোজ হিসাব",
    climateAlert: "জলবায়ু সতর্কতা",
    climateDesc: "দুর্যোগ সতর্কতা",
    govServices: "সরকারি সেবা",
    govDesc: "ভর্তুকি ও ঋণ",
    storage: "গুদাম ব্যবস্থাপনা",
    storageDesc: "ফসল রাখা",
    history: "ফসল ইতিহাস",
    historyDesc: "আগের স্ক্যান দেখ",
    rewards: "পুরস্কার",
    rewardsDesc: "ব্যাজ ও পয়েন্ট",
    fertilizerAdvice: "সার পরামর্শ",
    fertAdviceDesc: "সার সুপারিশ",
    knowledge: "খেতি জ্ঞান",
    knowledgeDesc: "শিখ ও জান",
    community: "কমিউনিটি",
    communityDesc: "কৃষক সংঘ",
    appGuide: "অ্যাপ গাইড",
    guideDesc: "টিউটোরিয়াল দেখ",
    landCalculator: "জমি হিসাব",
    landDesc: "জমির মাপ ও দাম",
    impactAnalytics: "প্রভাব বিশ্লেষণ",
    impactDesc: "সমস্যা সমাধান চার্ট",
    
    // Bottom Nav
    scanner: "স্ক্যানার",
    aiChat: "AI চ্যাট",
    support: "সাপোর্ট",
    
    // Header
    loggedIn: "লগইন আছ",
    welcome: "স্বাগতম!",
    welcomeBack: "স্বাগতম!",
    getStarted: "শুরু কর",
    createAccount: "একাউন্ট খোল",
    account: "একাউন্ট",
    profile: "প্রোফাইল",
    logout: "লগআউট",
    login: "লগইন / রেজিস্টার",
    loginTitle: "লগইন কর",
    registerTitle: "রেজিস্টার কর",
    findingLocation: "লোকেশন খুঁজতেসি...",
    adminDashboard: "অ্যাডমিন ড্যাশবোর্ড",
    
    // Stats
    scans: "স্ক্যান",
    level: "লেভেল",
    rank: "র‍্যাংক",
    
    // Tips
    todayTip: "আজকার টিপস",
    
    // Market
    rice: "ধান",
    potato: "আলু",
    onion: "পিয়াজ",
    weeklyAvg: "সাপ্তাহিক গড়",
    perKg: "টাহা/কেজি",
    
    // Weather
    humidity: "আর্দ্রতা",
    wind: "বাতাস",
    feelsLike: "অনুভব",
    
    // Settings
    customizeApp: "অ্যাপ কাস্টমাইজ কর",
    language: "ভাষা",
    bangla: "বাংলা",
    english: "English",
    chittagongian: "চাটগাইয়া",
    noakhalian: "নোয়াখাইল্লা",
    notifications: "নোটিফিকেশন",
    pushNotifications: "পুশ নোটিফিকেশন",
    weatherMarketUpdate: "আবহাওয়া ও বাজার আপডেট",
    smsNotifications: "SMS নোটিফিকেশন",
    importantAlerts: "গুরুত্বপূর্ণ সতর্কতা",
    namePhone: "নাম ও ফোন নম্বর",
    privacy: "গোপনীয়তা",
    dataProtection: "ডাটা সুরক্ষা সেটিংস",
    help: "সাহায্য",
    faq: "প্রশ্ন ও উত্তর",
    aboutApp: "অ্যাপ সম্পর্কে",
    version: "সংস্করণ ১.০.০",
    aiAssistantFull: "বাংলার কৃষকের AI সহকারী",
    createdBy: "Created by TEAM_NEWBIES",
    selectLanguage: "ভাষা বাছাই কর",
    chooseLanguage: "তোর পছন্দের ভাষা বাছাই কর",
    enterPhone: "ফোন নম্বর দে",
    phoneNumber: "ফোন নম্বর",
    smsSaved: "SMS নোটিফিকেশন চালু হইসে",
    smsDisabled: "SMS নোটিফিকেশন বন্ধ হইসে",
    languageChanged: "ভাষা বদলাইসে",
    validPhone: "ঠিক ফোন নম্বর দে",
    smsDescription: "SMS পাইতে মোবাইল নম্বর দে",
    theme: "থিম",
    darkLightMode: "ডার্ক/লাইট মোড",
    darkModeOn: "ডার্ক মোড চালু",
    lightModeOn: "লাইট মোড চালু",
    themeChanged: "থিম বদলাইসে",
    
    // Land Calculator
    landCalculatorTitle: "জমি হিসাব ক্যালকুলেটর",
    landCalculatorDesc: "জমির মাপ ও দাম হিসাব কর",
    enterLandSize: "জমির পরিমাণ দে",
    selectUnit: "একক বাছাই কর",
    bigha: "বিঘা",
    katha: "কাঠা",
    decimal: "শতক",
    acre: "একর",
    sqFeet: "বর্গফুট",
    sqMeter: "বর্গমিটার",
    calculate: "হিসাব কর",
    result: "ফলাফল",
    pricePerUnit: "প্রতি একক দাম (টাহা)",
    totalPrice: "মোট দাম",
    conversion: "রূপান্তর",
    reset: "রিসেট",
    
    // Offline
    offlineMode: "অফলাইন মোড",
    offlineMessage: "নেট নাই। সীমিত সুবিধা পাইবা।",
    
    // Chat
    askQuestion: "জিগা...",
    voiceInput: "ভয়েস ইনপুট",
    send: "পাঠাও",
    chatGreeting: "আসসালামু আলাইকুম! আমি agriশক্তি AI। তোর খেতির সমস্যায় সাহায্য করতে রেডি। কি জানতে চাও? 🌾",
    agriExpert: "খেতির বিশেষজ্ঞ সহকারী",
    suggestedQuestions: "প্রস্তাবিত প্রশ্ন",
    justNow: "এহনই",
    listening: "শুনতেসি...",
    speakBengali: "বাংলায় কথা কও",
    typeOrSpeak: "বাংলায় লেখ বা কও...",
    voiceHeard: "কথা শোনা হইসে",
    voiceError: "ভয়েস সমস্যা",
    chatHistoryCleared: "চ্যাট ইতিহাস মুছা গেসে",
    clearChatHistory: "চ্যাট ইতিহাস মুছ",
    clickMicToSpeak: "মাইক বাটনে ক্লিক কইরা বাংলায় কথা কও",
    sorryTempProblem: "মাফ কর, সাময়িক সমস্যা। আবার চেষ্টা কর।",
    errorGettingAnswer: "উত্তর পাইতে সমস্যা। আবার চেষ্টা কর।",
    sorryCantAnswer: "মাফ কর, উত্তর দিতে পারতেসি না।",
    listen: "শোন",
    chatQuestion1: "ধানের পাতা হলুদ হইতেসে ক্যান?",
    chatQuestion2: "কহন সার দেওন ঠিক?",
    chatQuestion3: "বৃষ্টিতে ফসল বাঁচামু ক্যামনে?",
    chatQuestion4: "পোকামাকড় মারমু ক্যামনে?",
    
    // Auth
    email: "ইমেইল",
    password: "পাসওয়ার্ড",
    fullName: "পুরা নাম",
    yourEmail: "তোর ইমেইল",
    yourPassword: "তোর পাসওয়ার্ড",
    yourFullName: "তোর পুরা নাম",
    minPassword: "কম হইলেও ৬ অক্ষর",
    bloodGroup: "রক্তের গ্রুপ",
    nationality: "জাতীয়তা",
    bangladeshi: "বাংলাদেশী",
    indian: "ভারতীয়",
    other: "অন্যান্য",
    select: "বাছাই কর",
    uploadPhoto: "ছবি দে",
    loginToAccount: "তোর একাউন্টে লগইন কর",
    createNewAccount: "নতুন একাউন্ট খোল",
    openAccount: "একাউন্ট খোল",
    loginBtn: "লগইন কর",
    signupBtn: "সাইনআপ কর",
    loginSuccess: "লগইন হইসে",
    logoutSuccess: "লগআউট হইসে",
    logoutError: "লগআউট করতে সমস্যা হইসে",
    accountCreated: "একাউন্ট খোলা হইসে!",
    fillAllFields: "সব তথ্য দে",
    fillNameEmailPass: "নাম, ইমেইল আর পাসওয়ার্ড দে",
    wrongEmailPass: "ইমেইল বা পাসওয়ার্ড ভুল",
    emailAlreadyUsed: "এই ইমেইল দিয়া আগেই একাউন্ট আছে",
    somethingWrong: "কিছু সমস্যা হইসে, আবার চেষ্টা কর",
    
    // Profile
    xpPoints: "XP পয়েন্ট",
    totalScans: "মোট স্ক্যান",
    daysActive: "সক্রিয় দিন",
    diseasesDetected: "রোগ শনাক্ত",
    editProfile: "প্রোফাইল সম্পাদনা",
    
    // Common Actions
    view: "দেখ",
    viewAll: "সব দেখ",
    more: "আরো",
    less: "কম",
    tryAgain: "আবার চেষ্টা কর",
    close: "বন্ধ কর",
    confirm: "নিশ্চিত কর",
    delete: "মুছ",
    edit: "সম্পাদনা",
    add: "যোগ কর",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("app-language");
    return (saved as Language) || "bn";
  });

  useEffect(() => {
    localStorage.setItem("app-language", language);
    // Update document lang attribute for accessibility
    document.documentElement.lang = language === "en" ? "en" : "bn";
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations["bn"][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
