// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/about-app.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var about_app_default = defineTool({
  name: "about_app",
  title: "About agri\u09B6\u0995\u09CD\u09A4\u09BF",
  description: "Returns a short description of the agri\u09B6\u0995\u09CD\u09A4\u09BF (Agri Shokti) app \u2014 a Bangla-first AI agriculture assistant for Bangladeshi farmers.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: [
          "agri\u09B6\u0995\u09CD\u09A4\u09BF (Agri Shokti) \u2014 \u09AE\u09BE\u099F\u09BF, \u09AE\u09BE\u09A8\u09C1\u09B7, \u09AA\u09CD\u09B0\u09AF\u09C1\u0995\u09CD\u09A4\u09BF \u2013 \u0995\u09C3\u09B7\u09BF\u09B0 \u09A8\u09A4\u09C1\u09A8 \u09B6\u0995\u09CD\u09A4\u09BF\u0964",
          "",
          "A Bangla-first AI assistant for Bangladeshi farmers, combining:",
          "- Crop disease detection (Gemini Vision)",
          "- Fertilizer packet scanner",
          "- NPK / land / machine calculators",
          "- NDVI satellite field health (Sentinel-2 / Landsat via AgroMonitoring)",
          "- Market prices, weather alerts, pest heatmap",
          "- BARI/BRRI-grounded RAG knowledge base",
          "",
          "Public site: https://agri-shokti-bangla.lovable.app"
        ].join("\n")
      }
    ]
  })
});

// src/lib/mcp/tools/get-weather.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
var get_weather_default = defineTool2({
  name: "get_weather",
  title: "Get weather forecast",
  description: "Get current weather and short-term forecast for a location in Bangladesh (or anywhere) using Open-Meteo. Provide latitude and longitude.",
  inputSchema: {
    latitude: z.number().min(-90).max(90).describe("Latitude in decimal degrees."),
    longitude: z.number().min(-180).max(180).describe("Longitude in decimal degrees.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ latitude, longitude }) => {
    const url = new URL("https://api.open-meteo.com/v1/forecast");
    url.searchParams.set("latitude", String(latitude));
    url.searchParams.set("longitude", String(longitude));
    url.searchParams.set(
      "current",
      "temperature_2m,relative_humidity_2m,precipitation,weather_code,wind_speed_10m"
    );
    url.searchParams.set(
      "daily",
      "temperature_2m_max,temperature_2m_min,precipitation_sum,weather_code"
    );
    url.searchParams.set("timezone", "Asia/Dhaka");
    url.searchParams.set("forecast_days", "5");
    const res = await fetch(url.toString());
    if (!res.ok) {
      const body = await res.text();
      return {
        content: [{ type: "text", text: `Open-Meteo error ${res.status}: ${body}` }],
        isError: true
      };
    }
    const data = await res.json();
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: data
    };
  }
});

// src/lib/mcp/tools/farming-tip.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var TIPS = {
  rice: [
    "\u09AC\u09CB\u09B0\u09CB \u09AE\u09CC\u09B8\u09C1\u09AE\u09C7 \u09B0\u09CB\u09AA\u09A3\u09C7\u09B0 \u09E8\u09E6-\u09E8\u09EB \u09A6\u09BF\u09A8 \u09AA\u09B0 \u0987\u0989\u09B0\u09BF\u09AF\u09BC\u09BE\u09B0 \u09AA\u09CD\u09B0\u09A5\u09AE \u0995\u09BF\u09B8\u09CD\u09A4\u09BF \u09AA\u09CD\u09B0\u09AF\u09BC\u09CB\u0997 \u0995\u09B0\u09C1\u09A8\u0964",
    "\u09A7\u09BE\u09A8\u09C7\u09B0 \u09AC\u09CD\u09B2\u09BE\u09B8\u09CD\u099F \u09B0\u09CB\u0997 \u09AA\u09CD\u09B0\u09A4\u09BF\u09B0\u09CB\u09A7\u09C7 \u09B8\u09B9\u09A8\u09B6\u09C0\u09B2 \u099C\u09BE\u09A4 (\u09AC\u09CD\u09B0\u09BF \u09A7\u09BE\u09A8\u09E8\u09EE, \u09EE\u09EF) \u09AC\u09CD\u09AF\u09AC\u09B9\u09BE\u09B0 \u0995\u09B0\u09C1\u09A8\u0964",
    "\u09B8\u09C7\u099A\u09C7\u09B0 \u09AA\u09BE\u09A8\u09BF \u099C\u09AE\u09BF\u09A4\u09C7 \u09EB-\u09ED \u09B8\u09C7\u09AE\u09BF \u09B0\u09BE\u0996\u09C1\u09A8, \u09AC\u09C7\u09B6\u09BF \u09A8\u09AF\u09BC\u0964"
  ],
  wheat: [
    "\u0997\u09AE\u09C7\u09B0 \u09AC\u09C0\u099C \u09AC\u09AA\u09A8\u09C7\u09B0 \u09B8\u09B0\u09CD\u09AC\u09CB\u09A4\u09CD\u09A4\u09AE \u09B8\u09AE\u09AF\u09BC: \u09E7\u09EB \u09A8\u09AD\u09C7\u09AE\u09CD\u09AC\u09B0 - \u09E9\u09E6 \u09A8\u09AD\u09C7\u09AE\u09CD\u09AC\u09B0\u0964",
    "\u09AC\u09C0\u099C \u09AC\u09AA\u09A8\u09C7\u09B0 \u09E8\u09E7 \u09A6\u09BF\u09A8 \u09AA\u09B0 \u09AA\u09CD\u09B0\u09A5\u09AE \u09B8\u09C7\u099A \u09A6\u09BF\u09A8\u0964"
  ],
  jute: [
    "\u09AA\u09BE\u099F\u09C7\u09B0 \u09AC\u09C0\u099C \u09AC\u09AA\u09A8\u09C7\u09B0 \u0986\u0997\u09C7 \u09B8\u09BE\u09B0\u09BF\u09A4\u09C7 \u09B8\u09BE\u09B0\u09BF\u09A4\u09C7 \u09AC\u09C0\u099C \u09B6\u09CB\u09A7\u09A8 \u0995\u09B0\u09C1\u09A8\u0964",
    "\u099A\u09BE\u09B0\u09BE \u0997\u099C\u09BE\u09A8\u09CB\u09B0 \u09E8\u09EB-\u09E9\u09E6 \u09A6\u09BF\u09A8\u09C7\u09B0 \u09AE\u09A7\u09CD\u09AF\u09C7 \u09AC\u09BF\u09B0\u09B2 \u0995\u09B0\u09BE \u09A6\u09B0\u0995\u09BE\u09B0\u0964"
  ],
  vegetable: [
    "\u09B8\u09AC\u099C\u09BF \u0995\u09CD\u09B7\u09C7\u09A4\u09C7 \u099C\u09C8\u09AC \u09B8\u09BE\u09B0 (\u0995\u09AE\u09CD\u09AA\u09CB\u09B8\u09CD\u099F) \u09AC\u09CD\u09AF\u09AC\u09B9\u09BE\u09B0 \u09AE\u09BE\u099F\u09BF\u09B0 \u09B8\u09CD\u09AC\u09BE\u09B8\u09CD\u09A5\u09CD\u09AF \u09AD\u09BE\u09B2\u09CB \u09B0\u09BE\u0996\u09C7\u0964",
    "\u099F\u09AE\u09C7\u099F\u09CB\u09B0 \u09A8\u09BE\u09AC\u09BF \u09A7\u09CD\u09AC\u09B8\u09BE \u09B0\u09CB\u0997 \u09AA\u09CD\u09B0\u09A4\u09BF\u09B0\u09CB\u09A7\u09C7 \u09B8\u0995\u09BE\u09B2\u09C7 \u09B8\u09C7\u099A \u09A6\u09BF\u09A8, \u09AC\u09BF\u0995\u09C7\u09B2\u09C7 \u09A8\u09AF\u09BC\u0964"
  ]
};
var farming_tip_default = defineTool3({
  name: "get_farming_tip",
  title: "Get farming tip",
  description: "Return a short Bangla farming tip for a given crop category. Categories: rice, wheat, jute, vegetable.",
  inputSchema: {
    crop: z2.enum(["rice", "wheat", "jute", "vegetable"]).describe("Crop category to get a tip for.")
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: false },
  handler: ({ crop }) => {
    const list = TIPS[crop] ?? [];
    const tip = list[Math.floor(Math.random() * list.length)] ?? "\u0995\u09CB\u09A8\u09CB \u099F\u09BF\u09AA \u09AA\u09BE\u0993\u09AF\u09BC\u09BE \u09AF\u09BE\u09AF\u09BC\u09A8\u09BF\u0964";
    return {
      content: [{ type: "text", text: tip }],
      structuredContent: { crop, tip }
    };
  }
});

// src/lib/mcp/tools/market-prices.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var SUPABASE_URL = "https://yojlbxpbxfskcfzfoghs.supabase.co";
var SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvamxieHBieGZza2NmemZvZ2hzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU0NDE2NjksImV4cCI6MjA4MTAxNzY2OX0.5imSdia4p717cVqBQctC0fmOtcpg3yoZiWEnrS3tC9g";
var market_prices_default = defineTool4({
  name: "get_market_prices",
  title: "Get market prices",
  description: "Fetch today's fresh bazaar prices for crops, vegetables, fish, poultry, and livestock in Bangladesh \u2014 including yesterday's price and day-over-day change. Optional filter by crop name (Bangla or English substring).",
  inputSchema: {
    crop: z3.string().nullable().describe(
      "Optional crop/item name filter (substring match, e.g. '\u09A7\u09BE\u09A8', 'rice', '\u0987\u09B2\u09BF\u09B6'). Pass null for all items."
    ),
    limit: z3.number().int().min(1).max(100).nullable().describe("Max rows to return (default 50). Pass null for default.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ crop, limit }) => {
    const url = new URL(`${SUPABASE_URL}/rest/v1/market_prices`);
    url.searchParams.set(
      "select",
      "crop_name,crop_emoji,today_price,yesterday_price,weekly_avg,forecast_price,unit,market_location,forecast,confidence,updated_at"
    );
    url.searchParams.set("order", "updated_at.desc");
    url.searchParams.set("limit", String(limit ?? 50));
    if (crop && crop.trim()) {
      url.searchParams.set("crop_name", `ilike.*${crop.trim()}*`);
    }
    const res = await fetch(url.toString(), {
      headers: {
        apikey: SUPABASE_ANON_KEY,
        Authorization: `Bearer ${SUPABASE_ANON_KEY}`
      }
    });
    if (!res.ok) {
      const body = await res.text();
      return {
        content: [{ type: "text", text: `Market prices error ${res.status}: ${body}` }],
        isError: true
      };
    }
    const rows = await res.json();
    const items = rows.map((r) => {
      const today = Number(r.today_price ?? 0);
      const yest = Number(r.yesterday_price ?? 0);
      const change = today - yest;
      const changePct = yest ? change / yest * 100 : 0;
      return {
        crop: r.crop_name,
        emoji: r.crop_emoji,
        today_price: today,
        yesterday_price: yest,
        change,
        change_pct: Number(changePct.toFixed(2)),
        weekly_avg: r.weekly_avg,
        forecast_price: r.forecast_price,
        forecast: r.forecast,
        confidence: r.confidence,
        unit: r.unit,
        market: r.market_location,
        updated_at: r.updated_at
      };
    });
    const summary = items.map(
      (i) => `${i.emoji ?? ""} ${i.crop}: \u0986\u099C \u09F3${i.today_price}/${i.unit ?? ""} \xB7 \u0997\u09A4\u0995\u09BE\u09B2 \u09F3${i.yesterday_price} \xB7 \u09AA\u09B0\u09BF\u09AC\u09B0\u09CD\u09A4\u09A8 ${i.change >= 0 ? "+" : ""}${i.change} (${i.change_pct}%)${i.market ? ` \xB7 ${i.market}` : ""}`
    ).join("\n");
    return {
      content: [
        {
          type: "text",
          text: summary || "No market prices found for that filter."
        }
      ],
      structuredContent: { count: items.length, items }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "agrishokti-mcp",
  title: "agri\u09B6\u0995\u09CD\u09A4\u09BF MCP",
  version: "0.2.0",
  instructions: "Public tools for the agri\u09B6\u0995\u09CD\u09A4\u09BF (Agri Shokti) Bangla-first agriculture app. Use `about_app` to introduce the app, `get_weather` for Open-Meteo forecasts by lat/lng, `get_farming_tip` for a short Bangla tip by crop category, and `get_market_prices` for today's/yesterday's bazaar prices (crops, vegetables, fish, poultry, livestock) with day-over-day change \u2014 call this whenever the user asks about \u09A6\u09BE\u09AE / \u09AC\u09BE\u099C\u09BE\u09B0 / market price.",
  tools: [about_app_default, get_weather_default, farming_tip_default, market_prices_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
